### ISSUE TITLE
Rewrite with pdf.rs and Pathfinder

### ISSUE THREAD

**Issue by chardoncs** [chardoncs/kurumi#2]
Due to the complexity of `gtk4-rs` and dependency of shared library Poppler, I would like to switch to a native and more cross-platform (-ish) stack.

## Tasks

- [ ] Use iced or other libraries, or native wgpu UI implementation (if necessary)
- [ ] Port Pathfinder and UI onto wgpu
- [ ] PDF manipulation (optional)

## Extra

License: Dual (Apache-2.0 or MIT) -> MIT
